services:
  - type: web
    name: portfolio-frontend
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    routes:
      - type: rewrite
        source: /proyectos
        destination: /index.html
      - type: rewrite
        source: /*
        destination: /index.html 